Controllers/ResearchController.cs
using Reseaarch_Alliances.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Reseaarch_Alliances.Controllers
{
    public class ResearchController : Controller
    {
        ResearchAlliances res = new ResearchAlliances();

        // GET: Research
        public ActionResult Index()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                return View(res.tblresearches.ToList());
            }
        }

        public ActionResult ResearchInfo(int id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                int uid = Convert.ToInt32(Session["UserID"]);
                bool isRequestSend = res.tblresearchrequests.ToList().Exists(t => t.UserID == uid && t.ResearchID == id);
                ViewBag.isRequestSend = isRequestSend;
                bool isFollowed = res.tblresearchfollowers.ToList().Exists(t => t.UserID == uid && t.ResearchID == id);
                ViewBag.isFollowed = isFollowed;
                ViewData["researchUpdates"] = res.tblresearchupdates.Where(t => t.ResearchID == id).ToList();
                ViewData["researchUpdateLikes"] = res.tblresearchupdatelikes.ToList();
                return View(res.tblresearches.Where(t => t.ResearchID == id).SingleOrDefault());
            }
        }

        public ActionResult AddResearch()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult AddResearch(tblresearch r,HttpPostedFileBase FeaturedImage)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                int uid = Convert.ToInt32(Session["UserID"]);
                var fileName = Path.GetFileName(FeaturedImage.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/Images/Research"), fileName);
                FeaturedImage.SaveAs(path);

                r.UserID = uid;
                r.FeaturedImage = fileName;

                res.tblresearches.Add(r);

                res.SaveChanges();

                return RedirectToAction("Index", "User", new { id = uid });
            }
        }

        public ActionResult removeResearch(int id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                int uid = Convert.ToInt32(Session["UserID"]);

                tblresearch r = res.tblresearches.Where(t => t.ResearchID == id).SingleOrDefault();
                res.tblresearches.Remove(r);

                res.SaveChanges();

                return RedirectToAction("Index", "User", new { id = uid });
            }
        }

        public ActionResult followRshRequest(int rid)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                int uid = Convert.ToInt32(Session["UserID"]);

                tblresearchrequest rshReq = new tblresearchrequest();
                rshReq.UserID = uid;
                rshReq.ResearchID = rid;

                res.tblresearchrequests.Add(rshReq);
                res.SaveChanges();

                return View();
            }
        }

        public ActionResult UnfollowRsh(int rid)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                int uid = Convert.ToInt32(Session["UserID"]);

                tblresearchfollower resFol = res.tblresearchfollowers.Where(t => t.ResearchID == rid && t.UserID == uid).SingleOrDefault();

                res.tblresearchfollowers.Remove(resFol);
                res.SaveChanges();

                return View(res.tblresearches.Where(t => t.ResearchID == rid).SingleOrDefault());
            }
        }


        public ActionResult AcceptRejectReq(int id,int op)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                int uid = Convert.ToInt32(Session["UserID"]);
                tblresearchrequest resReq = res.tblresearchrequests.Where(t => t.ResearchRequestID == id).SingleOrDefault();
                if (op == 0)
                {
                    tblresearchfollower resFol = new tblresearchfollower();
                    resFol.ResearchID = resReq.ResearchID;
                    resFol.UserID = resReq.UserID;

                    res.tblresearchfollowers.Add(resFol);
                }
                res.tblresearchrequests.Remove(resReq);
                res.SaveChanges();
                return RedirectToAction("Index", "User", new { id = uid });
            }
        }

        public ActionResult EditResearch(int id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                return View(res.tblresearches.Where(t => t.ResearchID == id).SingleOrDefault());
            }
        }

        [HttpPost]
        public ActionResult UpdateResearch(tblresearch r)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                tblresearch rsh = res.tblresearches.Where(t => t.ResearchID == r.ResearchID).SingleOrDefault();
                rsh.Title = r.Title;
                rsh.Description = r.Description;

                res.SaveChanges();
                return RedirectToAction("Index", "User", new { id = rsh.UserID });
            }
        }

        public ActionResult EditFeaturedResearch(int id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                return View(res.tblresearches.Where(t => t.ResearchID == id).SingleOrDefault());
            }
        }

        [HttpPost]
        public ActionResult UpdateFeaturedResearch(tblresearch r, HttpPostedFileBase FeaturedImage)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                tblresearch rsh = res.tblresearches.Where(t => t.ResearchID == r.ResearchID).SingleOrDefault();
                var fileName = Path.GetFileName(FeaturedImage.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/Images/Research"), fileName);
                FeaturedImage.SaveAs(path);

                rsh.FeaturedImage = fileName;

                res.SaveChanges();

                return RedirectToAction("Index", "User", new { id = rsh.UserID });
            }
        }

        [HttpPost]
        public ActionResult postRshUpdate(int rid)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                string rshDesc = Request["rshDesc"].ToString();
                int uid = Convert.ToInt32(Session["UserID"]);

                tblresearchupdate rshUpd = new tblresearchupdate();
                rshUpd.ResearchID = rid;
                rshUpd.UpdateDescription = rshDesc;
                rshUpd.UserID = uid;

                res.tblresearchupdates.Add(rshUpd);

                res.SaveChanges();

                return RedirectToAction("ResearchInfo", new { id = rid });
            }
        }

        public ActionResult likeUnlikeUpdate(int ruid)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("LogIn", "User");
            }
            else
            {
                int uid = Convert.ToInt32(Session["UserID"]);
                bool isAvailable = res.tblresearchupdatelikes.ToList().Exists(t => t.ResearchUpdateID == ruid && t.UserID == uid);
                if (isAvailable)
                {
                    tblresearchupdatelike alk = res.tblresearchupdatelikes.Where(t => t.ResearchUpdateID == ruid && t.UserID == uid).SingleOrDefault();
                    res.tblresearchupdatelikes.Remove(alk);
                }
                else
                {
                    tblresearchupdatelike alk = new tblresearchupdatelike();
                    alk.UserID = uid;
                    alk.ResearchUpdateID = ruid;

                    res.tblresearchupdatelikes.Add(alk);
                }
                res.SaveChanges();
                ViewBag.isliked = isAvailable;
                return View();
            }
        }
    }
}

Views/Research/AddResearch.cshtml
@model Reseaarch_Alliances.Models.tblresearch

@{
    ViewBag.Title = "Add Research";
    Layout = "~/Views/Shared/_User.cshtml";
}
}

<div class="contact--section pt--50">
    <div class="container">

        <div class="col-md-12 pb--60">
            <!-- Contact Form Start -->
            <div class="contact--form" data-form="ajax">
                <div class="contact--title">
                    <h3 class="h4">Add Research</h3>
                </div>

                @using (Html.BeginForm("AddResearch", "Research", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Description,5,120, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.SubCategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10" id="SubCat">
                                <select name="subcategory" class="form-control">
                                    <option value=""></option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.FeaturedImage, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <input type="file" name="FeaturedImage" accept=".jpg,.jpeg,.png" />
                                @Html.ValidationMessageFor(model => model.FeaturedImage, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
            <!-- Contact Form End -->
        </div>
    </div>
</div>

<script>

    window.onload = getAllSubCategory;

    function getAllSubCategory() {
        $.ajax({
            url: "@Url.Action("getAllSubCategory","Articles")",
            success: function (result) {
                $("#SubCat").html(result);
            }
        });
    }

</script>

Views/Research/EditFeaturedResearch.cshtml
@model Reseaarch_Alliances.Models.tblresearch

@{
    ViewBag.Title = "EditFeaturedResearch";
    Layout = "~/Views/Shared/_User.cshtml";
}

    <div class="contact--section pt--50">
        <div class="container">

            <div class="col-md-12 pb--60">
                <!-- Contact Form Start -->
                <div class="contact--form" data-form="ajax">
                    <div class="contact--title">
                        <h3 class="h4">Update Featured Image</h3>
                    </div>
                    @using (Html.BeginForm("UpdateFeaturedResearch", "Research", FormMethod.Post,new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.ResearchID)

                            <div class="form-group">
                                @Html.LabelFor(model => model.FeaturedImage, htmlAttributes: new { @class = "control-label col-md-2" })
                                <input type="file"  class="form-control" name="FeaturedImage" id="FeaturedImage" />
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Update" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                </div>
                <!-- Contact Form End -->
            </div>
        </div>
    </div>

Views/Research/EditResearch.cshtml
@model Reseaarch_Alliances.Models.tblresearch

@{
    ViewBag.Title = "Edit Research";
    Layout = "~/Views/Shared/_User.cshtml";
}

<div class="contact--section pt--50">
    <div class="container">

        <div class="col-md-12 pb--60">
            <!-- Contact Form Start -->
            <div class="contact--form" data-form="ajax">
                <div class="contact--title">
                    <h3 class="h4">Edit Research</h3>
                </div>
                @using (Html.BeginForm("UpdateResearch","Research",FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ResearchID)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Description,5,120, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Update" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

            </div>
            <!-- Contact Form End -->
        </div>
    </div>
</div>

<script>

    window.onload = getAllSubCategory;

    function getAllSubCategory() {
        $.ajax({
            url: "@Url.Action("getAllSubCategory","Articles")",
            success: function (result) {
                $("#SubCat").html(result);
            }
        });
    }

</script>

Views/Research/Index.cshtml
@model IEnumerable<Reseaarch_Alliances.Models.tblresearch>

@{
    ViewBag.Title = "Researches";
    Layout = "~/Views/Shared/_User.cshtml";
}


<!-- Page Header Start -->
<div class="page--header pt--60 pb--60 text-center" data-bg-img="img/page-header-img/bg.jpg" data-overlay="0.85">
    <div class="container">
        <div class="title">
            <h2 class="h1 text-white">Researches</h2>
        </div>

        <ul class="breadcrumb text-gray ff--primary">
            <li><a href="#" class="btn-link">Home</a></li>
            <li class="active"><span class="text-primary">Researches</span></li>
        </ul>
    </div>
</div>
<!-- Page Header End -->
<!-- Page Wrapper Start -->
<section class="page--wrapper pt--80 pb--20">
    <div class="container">
        <div class="row">
            <!-- Main Content Start -->
            <div class="main--content col-md-12 pb--30">
                <div class="main--content-inner">
                    <div class="row AdjustRow">
                        @foreach (var item in Model)
                        {
                            <div class="col-md-3 col-xs-6 col-xxs-12 pb--30">
                                <!-- Product Item Start -->
                                <div class="product--item" data-scroll-reveal="bottom">
                                    <!-- Product Image Start -->
                                    <div class="product--img">
                                        <img src="~/Content/Images/Research/@item.FeaturedImage" alt="">

                                        <div class="action">
                                            <a href="@Url.Action("ResearchInfo","Research",new { id=item.ResearchID })">
                                                <i class="fa fa-eye"></i>
                                                <span>View Details</span>
                                            </a>
                                        </div>
                                    </div>
                                    <!-- Product Image End -->
                                    <!-- Product Info Start -->
                                    <div class="product--info text-center">
                                        <div class="title">
                                            <h3 class="h4">
                                                <a href="@Url.Action("ResearchInfo","Research",new { id=item.ResearchID })" class="btn-link" style="text-transform:capitalize;font-size:1.2em">@item.Title</a>
                                            </h3>
                                        </div>
                                        <div class="cat">
                                            <p>
                                                <i class="fa fa-tag" style="margin-right:5px"></i>@item.tblsubcategory.SubCategoryName
                                            </p>
                                        </div>

                                        <div class="price text-darkest">
                                            <p><span class="text-default mr--15">@item.CreatedDt</span></p>
                                        </div>

                                    </div>
                                    <!-- Product Info End -->
                                </div>
                                <!-- Product Item End -->
                            </div>
                        }
                    </div>
                </div>
            </div>
            <!-- Main Content End -->
        </div>
    </div>
</section>
<!-- Page Wrapper End -->

Views/Research/ResearchInfo.cshtml
@model Reseaarch_Alliances.Models.tblresearch

@{
    ViewBag.Title = "Research Info";
    Layout = "~/Views/Shared/_User.cshtml";


    IEnumerable<Reseaarch_Alliances.Models.tblresearchupdatelike> researchUpdateLikes = ViewData["researchUpdateLikes"] as IEnumerable<Reseaarch_Alliances.Models.tblresearchupdatelike>;
    IEnumerable<Reseaarch_Alliances.Models.tblresearchupdate> researchUpdates = ViewData["researchUpdates"] as IEnumerable<Reseaarch_Alliances.Models.tblresearchupdate>;
}

<!-- Page Header Start -->
<div class="page--header pt--60 pb--60 text-center" data-bg-img="img/page-header-img/bg.jpg" data-overlay="0.85">
    <div class="container">
        <div class="title">
            <h2 class="h1 text-white">Research Details</h2>
        </div>

        <ul class="breadcrumb text-gray ff--primary">
            <li><a href="#" class="btn-link">Home</a></li>
            <li><a href="#" class="btn-link">Researches</a></li>
            <li class="active"><span class="text-primary">Research Details</span></li>
        </ul>
    </div>
</div>
<!-- Page Header End -->
<!-- Page Wrapper Start -->
<section class="page--wrapper pt--80 pb--20">
    <div class="container">
        <!-- Main Content Start -->
        <div class="main--content col-md-12" data-trigger="stickyScroll">
            <div class="main--content-inner">
                <div class="col-md-12 col-sm-12 pb--60">
                    <!-- Product Gallery Start -->
                    <div class="product--gallery">
                        <!-- Tab Content Start -->
                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="productImg01">
                                <div data-trigger="zoom">
                                    <img src="~/Content/Images/Research/@Model.FeaturedImage" alt="">
                                </div>
                            </div>
                        </div>
                        <!-- Tab Content End -->
                        <!-- Owl Carousel End -->
                    </div>
                    <!-- Product Gallery End -->
                </div>

                <div class="col-md-12 col-sm-12 pb--60">
                    <div class="col-md-3 float--right" id="followUnfollow">
                        @if (Model.UserID != Convert.ToInt32(Session["UserID"]))
                        {
                            if (ViewBag.isRequestSend)
                            {
                                <a class="btn btn-info font-weight-lighter" href="#" style="margin:10px">Follow Request Send</a>
                            }
                            else if (ViewBag.isFollowed)
                            {
                                <a class="btn btn-info font-weight-lighter" onclick="UnfollowRsh(@Model.ResearchID)" style="margin:10px">Unfollow</a>
                            }
                            else
                            {
                                <a class="btn btn-info font-weight-lighter" onclick="followRshRequest(@Model.ResearchID)" style="margin:10px">Follow</a>
                            }
                        }


                    </div>
                    <!-- Product Summery Start -->
                    <div class="product--summery fs--14">

                        <div class="title">
                            <font style="font-size:3em;color:black">@Model.Title</font>
                        </div>

                        <div class="review--count text-darkest">
                            <p>
                                <a href="#" class="btn-link">
                                    <i class="mr--8 text-default fa fa-tag"></i>
                                    <span>@Model.tblsubcategory.SubCategoryName</span>
                                </a>
                            </p>
                            <p>
                                <a href="#" class="btn-link">
                                    <i class="mr--8 text-default fa fa-calendar"></i>
                                    <span>@Model.CreatedDt</span>
                                </a>
                            </p>
                        </div>


                        <div class="desc border-bottom border-dark">
                            <p style="font-size:1.3em;margin-bottom:15px">
                                @Model.Description
                            </p>
                        </div>
                    </div>
                    <!-- Product Summery End -->
                </div>


                @if (ViewBag.isFollowed)
                {
                    <!-- Product Details Nav Start -->
                    <div class="product--details-nav">
                        <ul class="nav ff--primary fs--18 fw--600 text-black bg-lighter">
                            <li class="active">
                                <a href="#produtDetailsTab01" data-toggle="tab">Research Updates</a>
                            </li>
                        </ul>
                    </div>
                    <!-- Product Details Nav End -->
                    <!-- Product Details Start -->
                    <div class="product--details tab-content pb--60">
                        <!-- Tab Pane Start -->
                        <form method="post" action="@Url.Action("postRshUpdate","Research",new { rid=Model.ResearchID })">
                            <div class="form-group" style="margin-top:30px">
                                <label class="control-label col-md-2 font-weight-bold" style="font-size:1.5em">Update Research</label>
                                <div class="col-md-11" style="margin-top:10px">
                                    <textarea rows="5" name="rshDesc" class="form-control"></textarea>
                                </div>
                                <div class="col-md-3" style="margin-top:10px">
                                    <input type="submit" value="Update" class="btn btn-info" />
                                </div>
                            </div>

                        </form>
                    </div>
                    <!-- Product Details End -->

                    <div class="col-md-12" style="margin-top:30px">
                        <h3>Updates</h3>
                        @foreach (var item in researchUpdates)
                        {
                            <div class="topic--reply" style="margin-top:15px">
                                <div class="header clearfix">
                                    <p class="date float--left">@item.CreatedDt</p>
                                </div>

                                <div class="body clearfix">
                                    <div class="author mr--20 float--left text-center">
                                        <div class="avatar" data-overlay="0.3" data-overlay-color="primary">
                                            <a href="@Url.Action("Index","User",new { id=item.UserID })">
                                                <img src="~/Content/Images/User/@item.tbluser.ProfilePic" alt="">
                                            </a>
                                        </div>

                                        <div class="name text-darkest">
                                            <p><a href="@Url.Action("Index","User",new { id=item.UserID })">@item.tbluser.UserName</a></p>
                                        </div>
                                    </div>

                                    <div class="content pt--20 fs--14 ov--h" style="margin-left:15px">
                                        <p style="font-weight:bolder;font-size:1.5em">
                                            @item.UpdateDescription
                                        </p>
                                        <a class="text-decoration-none" id="like_@item.ResearchUpdateID" onclick="likeUnlikeUpdate(@item.ResearchUpdateID)">
                                            @{
                                                int uid = Convert.ToInt32(Session["UserID"]);
                                                bool isAvailable = researchUpdateLikes.ToList().Exists(t => t.ResearchUpdateID == item.ResearchUpdateID && t.UserID == uid);
                                            }
                                            @if (isAvailable)
                                            {
                                                <i class="fa fa-heart" style="color:red;font-size:1.5em;margin-left:10px"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-heart-o" style="color:red;font-size:1.5em;margin-left:10px"></i>
                                            }

                                        </a>
                                        
                                    </div>
                                </div>
                            </div>


                        }
                    </div>
                }


            </div>
        </div>
        <!-- Main Content End -->
    </div>
</section>
<!-- Page Wrapper End -->

<script>

    function followRshRequest(id) {
        $.ajax({
            url: "@Url.Action("followRshRequest","Research")?rid="+id,
            success: function (result) {
                $("#followUnfollow").html(result);
            }
        });
    }

    function UnfollowRsh(id) {
        $.ajax({
            url: "@Url.Action("UnfollowRsh","Research")?rid="+id,
            success: function (result) {
                $("#followUnfollow").html(result);
            }
        });
    }

    function likeUnlikeUpdate(id) {
        var uid = id;
        $.ajax({
            url: "@Url.Action("likeUnlikeUpdate","Research")?ruid="+id,
            success: function (result) {
                $("#like_"+uid).html(result);
            }
        });
    }

</script>

Views/Research/UnfollowRsh.cshtml
@model Reseaarch_Alliances.Models.tblresearch

@{
    Layout = null;
}

    <a class="btn btn-info font-weight-lighter" onclick="UnfollowRsh(@Model.ResearchID)" style="margin:10px">Follow</a>

Views/Research/followRshRequest.cshtml
@{
    Layout = null;
}

<a class="btn btn-info font-weight-lighter" style="margin:10px">Follow Request Send</a>

Views/Research/likeUnlikeUpdate.cshtml
@{
    Layout = null;
}

@if (ViewBag.isliked)
{
    <i style="color:red;font-size:1.5em;margin-left:10px" class="fa fa-heart-o"></i>
}
else
{
    <i style="color:red;font-size:1.5em;margin-left:10px" class="fa fa-heart"></i>
}